name: thechaigatecounsel
favicon: null
layout_spectrum: 0.7557214100379497
typography_spectrum: 0.07222664123401046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8840127163566649
  lightness: 0.40121308784000576
  saturation: 0.36204003007151186
  rhythmicContrast: 0.48659345763735473
purpose: []
